# Generated by Django 2.0.4 on 2018-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Impuesto3 %'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_taxes3',
            field=models.BooleanField(default=False, verbose_name='Usa impuesto 3?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Impuesto1 %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use_taxes',
            field=models.BooleanField(default=False, verbose_name='Usa impuesto 1?'),
        ),
    ]
