# Generated by Django 2.0.4 on 2018-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180425_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.CharField(blank=True, default='00', max_length=2, verbose_name='Código impuesto 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code2',
            field=models.CharField(blank=True, default='00', max_length=2, verbose_name='Código impuesto 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code3',
            field=models.CharField(blank=True, default='00', max_length=2, verbose_name='Código impuesto 3'),
        ),
    ]
