# Generated by Django 2.0.4 on 2018-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180503_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subdepartment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sub-Familia'),
        ),
    ]
