# Generated by Django 2.0.4 on 2018-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180503_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_code3',
            field=models.CharField(blank=True, default='00', max_length=2, null=True, verbose_name='Código impuesto 3'),
        ),
    ]
