# Generated by Django 2.0.4 on 2018-04-21 20:27

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, default='0000', max_length=4, null=True, verbose_name='PIN')),
                ('avatar', models.ImageField(blank=True, upload_to=apps.profiles.models.url)),
                ('id_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
