# Generated by Django 2.0.4 on 2018-05-11 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('consecutive', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Número de factura')),
                ('client', models.TextField(default='', verbose_name='Objeto Cliente')),
                ('client_id', models.CharField(default='1', max_length=255, verbose_name='Id de Cliente')),
                ('user', models.TextField(default='', verbose_name='Objeto Usuario')),
                ('amount', models.FloatField(default=0, verbose_name='Monto del avance')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Adelanto de efectivo',
                'verbose_name_plural': 'Adelantos de efectivo',
                'ordering': ['consecutive'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('consecutive', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Número de factura')),
                ('cart', models.TextField(default='', verbose_name='Objeto Carrito')),
                ('client', models.TextField(default='', verbose_name='Objeto Cliente')),
                ('client_id', models.CharField(default='1', max_length=255, verbose_name='Id de Cliente')),
                ('pay', models.TextField(default='', verbose_name='Objeto Pago')),
                ('pay_type', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('CRED', 'Crédito'), ('TRAN', 'Transferencia'), ('OTHE', 'Otro')], default='CASH', max_length=4, verbose_name='Tipo de Pago')),
                ('payed', models.BooleanField(default=True, verbose_name='Pagada')),
                ('user', models.TextField(default='', verbose_name='Objeto Usuario')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['consecutive'],
            },
        ),
    ]
