# Generated by Django 2.0.4 on 2018-05-16 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_advance',
            name='sale_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='cash_advance',
            name='work_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
