# Generated by Django 2.0.4 on 2018-05-05 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advance_number', models.IntegerField(default=1, editable=False, verbose_name='Número de factura')),
                ('client', models.TextField(default='', verbose_name='Objeto Cliente')),
                ('client_id', models.CharField(default='1', max_length=255, verbose_name='Id de Cliente')),
                ('user', models.TextField(default='', verbose_name='Objeto Usuario')),
                ('amount', models.FloatField(default=0, verbose_name='Monto del avance')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Adelanto de efectivo',
                'verbose_name_plural': 'Adelantos de efectivo',
                'ordering': ['advance_number'],
            },
        ),
    ]
