# Generated by Django 2.0.4 on 2018-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180516_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_advance',
            name='sale_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash_advance',
            name='work_order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
