# Generated by Django 2.0.4 on 2018-05-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cash_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_advance',
            name='advance_number',
            field=models.IntegerField(default=1, editable=False, unique=True, verbose_name='Número de factura'),
        ),
    ]
