# Generated by Django 2.0.4 on 2018-05-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180505_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bill_number',
            field=models.IntegerField(default=1, editable=False, unique=True, verbose_name='Número de factura'),
        ),
    ]
