# Generated by Django 2.0.4 on 2018-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180516_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_advance',
            name='sale_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la venta'),
        ),
    ]
