# Generated by Django 2.0.4 on 2018-04-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='value',
        ),
    ]
