# Generated by Django 2.0.4 on 2018-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_remove_tax_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
