# Generated by Django 2.0.4 on 2018-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_movement',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Monto'),
        ),
    ]
