# Generated by Django 2.0.4 on 2018-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_movement',
            name='credit_note_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto nota de crédito'),
        ),
        migrations.AddField(
            model_name='credit_movement',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto Pago'),
        ),
        migrations.AlterField(
            model_name='credit_movement',
            name='bill_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto Factura'),
        ),
        migrations.AlterField(
            model_name='credit_movement',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto Cliente'),
        ),
    ]
