# Generated by Django 2.0.4 on 2018-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20180501_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_movement',
            name='debit_note_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto nota de débito'),
        ),
    ]
