# Generated by Django 2.0.4 on 2018-05-02 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_credit_movement_debit_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de movimiento')),
                ('sales', models.TextField(default='', verbose_name='Objeto Array de Facturas')),
                ('user', models.TextField(default='', verbose_name='Objeto Usuario')),
                ('client', models.TextField(default='', verbose_name='Objeto Cliente')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del movimiento')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Pago de Crédito',
                'verbose_name_plural': 'Pagos de Crédito',
                'ordering': ['payment_number'],
            },
        ),
    ]
