# Generated by Django 2.0.4 on 2018-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_credit_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_movement',
            name='is_null',
            field=models.BooleanField(default=False, verbose_name='Anulado?'),
        ),
        migrations.AddField(
            model_name='credit_payment',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Objeto Cliente'),
        ),
        migrations.AddField(
            model_name='credit_payment',
            name='is_null',
            field=models.BooleanField(default=False, verbose_name='Anulado?'),
        ),
    ]
