# Generated by Django 2.0.4 on 2018-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_auto_20180507_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_movement',
            name='movement_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True, verbose_name='Número de movimiento'),
        ),
    ]
