# Generated by Django 2.0.4 on 2018-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_auto_20180507_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_movement',
            name='movement_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de movimiento'),
        ),
    ]
