# Generated by Django 2.0.4 on 2018-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='1', max_length=1, verbose_name='Código de cantón')),
                ('name', models.CharField(default='San José', max_length=80, verbose_name='Cantón')),
                ('province_code', models.CharField(default='1', max_length=1, verbose_name='Código de provincia')),
            ],
            options={
                'verbose_name': 'Canton',
                'verbose_name_plural': 'Cantones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='1', max_length=1, verbose_name='Código de cantón')),
                ('name', models.CharField(default='CARMEN', max_length=80, verbose_name='Distrito')),
                ('province_code', models.CharField(default='1', max_length=1, verbose_name='Código de Provincia')),
                ('canton_code', models.CharField(default='1', max_length=1, verbose_name='Código de cantón')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='1', max_length=1, verbose_name='Código de provincia')),
                ('name', models.CharField(default='San José', max_length=80, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='1', max_length=1, verbose_name='Código de cantón')),
                ('name', models.CharField(default='Amón', max_length=80, verbose_name='Barrio')),
                ('province_code', models.CharField(default='1', max_length=1, verbose_name='Código de Provincia')),
                ('canton_code', models.CharField(default='1', max_length=2, verbose_name='Código de cantón')),
                ('district_code', models.CharField(default='1', max_length=2, verbose_name='Código de Distrito')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['code'],
            },
        ),
    ]
