# Generated by Django 2.0.4 on 2018-04-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'ordering': ['id'], 'verbose_name': 'Canton', 'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['id'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['id'], 'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
    ]
