# Generated by Django 2.0.4 on 2018-05-05 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de orden')),
                ('client_id', models.TextField(default='', verbose_name='Objeto Cliente')),
                ('article_data', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Datos del artículo')),
                ('malfunction_details', models.CharField(default='', max_length=255, verbose_name='Detalles falla')),
                ('observations', models.CharField(default='', max_length=255, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
            },
        ),
    ]
