# Generated by Django 2.0.4 on 2018-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_order',
            options={'ordering': ['order_number'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='work_order',
            name='article_brand',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='article_color',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='article_model',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='article_serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='article_type',
            field=models.CharField(default='', max_length=50, verbose_name='Tipo Electrodoméstico'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='client',
            field=models.TextField(default='', verbose_name='Objeto Cliente'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Orden Cerrada'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='receiving_employee',
            field=models.TextField(default='', verbose_name='Objeto Empleado'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='client_id',
            field=models.CharField(default='', max_length=40, verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='observations',
            field=models.TextField(default='', verbose_name='Observaciones'),
        ),
    ]
