# Generated by Django 2.0.4 on 2018-05-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20180507_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_order',
            options={'ordering': ['order_number'], 'permissions': (('list_work_order', 'Can list Work_Order'),), 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
    ]
