# Generated by Django 2.0.4 on 2018-05-07 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20180507_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(default='', max_length=40, verbose_name='ID Orden de Trabajo')),
                ('employee', models.TextField(default='', verbose_name='Empleado')),
                ('cost', models.FloatField(default=0, verbose_name='Costo Mano de Obra ₡')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción Reparación')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Parts_Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(default='', max_length=40, verbose_name='ID Orden de Trabajo')),
                ('employee', models.TextField(default='', verbose_name='Empleado')),
                ('part', models.TextField(default='', verbose_name='Objeto Parte')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.AddField(
            model_name='work_order',
            name='technician',
            field=models.TextField(default='', verbose_name='Tecnico a Cargo'),
        ),
    ]
