# Generated by Django 2.0.4 on 2018-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20180507_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_request',
            name='destination_warehouse',
            field=models.CharField(default='', max_length=40, verbose_name='Bodega de Destino'),
        ),
        migrations.AddField(
            model_name='parts_request',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'ENTRADA'), ('OUT', 'SALIDA')], default='', max_length=40, verbose_name='Tipo Movimiento'),
        ),
        migrations.AddField(
            model_name='parts_request',
            name='origin_warehouse',
            field=models.CharField(default='', max_length=40, verbose_name='Bodega de Origen'),
        ),
    ]
