# Generated by Django 2.0.4 on 2018-05-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20180507_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ['work_order_id'], 'permissions': (('list_labor', 'Can list Labor'),), 'verbose_name': 'Mano de Obra', 'verbose_name_plural': 'Mano de Obra'},
        ),
        migrations.AlterModelOptions(
            name='parts_request',
            options={'ordering': ['work_order_id'], 'permissions': (('list_part_request', 'Can list Part_Request'),), 'verbose_name': 'Solicitud de Parte', 'verbose_name_plural': 'Solicitudes de Parte'},
        ),
    ]
