# Generated by Django 2.0.4 on 2018-05-08 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20180507_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_order',
            options={'ordering': ['consecutive'], 'permissions': (('list_work_order', 'Can list Work_Order'),), 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='work_order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='work_order',
            name='consecutive',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='Número de orden'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
