# Generated by Django 2.0.4 on 2018-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20180508_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='is_warranty',
            field=models.BooleanField(default=False, verbose_name='Es una orden de Garantía?'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='warranty_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha venta en factura del producto'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='warranty_invoice_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de Factura de venta'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='warranty_number_bd',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de garantía Black&Decker'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='warranty_repaired_by',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada para entrega'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='warranty_supplier_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre de Comercio en factura'),
        ),
    ]
