# Generated by Django 2.0.4 on 2018-05-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20180511_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='consecutive',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Número de orden'),
        ),
    ]
