# Generated by Django 2.0.4 on 2018-05-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_auto_20180511_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='observations',
            new_name='observations_list',
        ),
    ]
