# Generated by Django 2.0.4 on 2018-05-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20180514_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Orden Pagada?'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Orden Cerrada?'),
        ),
    ]
