# Generated by Django 2.0.4 on 2018-05-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_auto_20180516_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labor',
            old_name='cost',
            new_name='amount',
        ),
    ]
