# Generated by Django 2.0.4 on 2018-05-18 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20180516_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(default='', max_length=40, verbose_name='ID Orden de Trabajo')),
                ('employee', models.TextField(default='', verbose_name='Empleado')),
                ('amount', models.FloatField(default=0, verbose_name='Costo Respuesto ₡')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción parte')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'permissions': (('list_used_part', 'Can list Used Parts'),),
                'verbose_name_plural': 'Repuestos Usados',
                'verbose_name': 'Repuesto Usado',
                'ordering': ['work_order_id'],
            },
        ),
        migrations.DeleteModel(
            name='Parts_Request',
        ),
    ]
