# Generated by Django 2.0.4 on 2018-05-21 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_auto_20180518_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(default='', max_length=40, verbose_name='ID Orden de Trabajo')),
                ('employee', models.TextField(default='', verbose_name='Empleado')),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('product', models.TextField(default='', verbose_name='Producto')),
                ('id_movement_workshop', models.UUIDField(verbose_name='ID movimiento Bodega de Taller')),
                ('id_movement_origin', models.UUIDField(verbose_name='ID movimeinto Bodega Origen')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Traslado de Repuesto',
                'ordering': ['work_order_id'],
                'permissions': (('list_part_request', 'Can list Parts request'),),
                'verbose_name_plural': 'Traslados de Repuesto',
            },
        ),
    ]
