# Generated by Django 2.0.4 on 2018-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_partrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='related_work_order',
            field=models.CharField(default='', max_length=40, verbose_name='ID Orden de Trabajo Asociada'),
        ),
    ]
