# Generated by Django 2.0.4 on 2018-05-04 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de movimiento')),
                ('movement_type', models.CharField(choices=[('INPUT', 'Ingreso'), ('OUTPUT', 'Salida'), ('ADJUST', 'Ajuste')], default='INPUT', max_length=4, verbose_name='Tipo de Movimiento')),
                ('user', models.TextField(default='', verbose_name='Objeto Usuario')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Monto')),
                ('product_id', models.CharField(max_length=255, verbose_name='ID del Producto')),
                ('product', models.TextField(default='', verbose_name='Objeto Producto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del movimiento')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Movimiento de Crédito',
                'verbose_name_plural': 'Movimientos de Crédito',
                'ordering': ['movement_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del movimiento')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Movimiento de Crédito',
                'verbose_name_plural': 'Movimientos de Crédito',
                'ordering': ['code'],
            },
        ),
    ]
