# Generated by Django 2.0.4 on 2018-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_movement',
            name='warehouse',
            field=models.TextField(default='', verbose_name='Objeto Bodega'),
        ),
    ]
