# Generated by Django 2.0.4 on 2018-05-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_inventory_movement_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_movement',
            name='is_null',
            field=models.BooleanField(default=False, verbose_name='Anulado?'),
        ),
    ]
