# Generated by Django 2.0.4 on 2018-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_inventory_movement_is_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_movement',
            name='product',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Objeto Producto'),
        ),
        migrations.AlterField(
            model_name='inventory_movement',
            name='user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Objeto Usuario'),
        ),
        migrations.AlterField(
            model_name='inventory_movement',
            name='warehouse',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Objeto Bodega'),
        ),
        migrations.AlterField(
            model_name='inventory_movement',
            name='warehouse_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la Bodega'),
        ),
    ]
