# Generated by Django 2.0.4 on 2018-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20180511_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_movement',
            name='id_generator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Generador'),
        ),
    ]
