# Generated by Django 2.0.4 on 2018-04-21 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('id_type', models.CharField(choices=[('PER', 'Cédula Física'), ('JUR', 'Cédula Jurídica'), ('PAS', 'Pasaporte')], default='PER', max_length=3, verbose_name='Tipo de Identificación')),
                ('id_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('cellphone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Agente')),
                ('agent_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos del Agente')),
                ('agent_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono del agente')),
                ('agent_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del Agente')),
                ('bank_accounts', models.TextField(blank=True, null=True, verbose_name='Cuentas Bancarias')),
                ('sinpe_accounts', models.TextField(blank=True, null=True, verbose_name='Cuentas SINPE')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['code'],
            },
        ),
    ]
