# Generated by Django 2.0.4 on 2018-05-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_movement',
            name='supplier',
            field=models.TextField(default='', verbose_name='Objeto Proveedor'),
        ),
    ]
