# Generated by Django 2.0.4 on 2018-05-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0002_credit_movement_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_movement',
            name='supplier',
        ),
    ]
