# Generated by Django 2.0.4 on 2018-04-21 20:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('id_type', models.CharField(choices=[('PER', 'Cédula Física'), ('JUR', 'Cédula Jurídica'), ('PAS', 'Pasaporte')], default='PER', max_length=3, verbose_name='Tipo de Identificación')),
                ('id_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('cellphone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('client_type', models.CharField(choices=[('GENERAL', 'Cliente General'), ('DISTRIB', 'Distribuidor'), ('WHOLESA', 'Mayorista')], default='GENERAL', max_length=7, verbose_name='Tipo de Cliente')),
                ('pred_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Predeterminado')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo')),
                ('max_line_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo por línea')),
                ('pays_taxes', models.BooleanField(default=True, verbose_name='Paga Impuestos?')),
                ('has_credit', models.BooleanField(default=False, verbose_name='Tiene Crédito?')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Límite de Crédito')),
                ('credit_days', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Días de Crédito')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['code'],
            },
        ),
    ]
