# Generated by Django 2.0.4 on 2018-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('01', 'Cédula Física'), ('02', 'Cédula Jurídica'), ('03', 'Pasaporte')], default='01', max_length=3, verbose_name='Tipo de Identificación'),
        ),
    ]
