# Generated by Django 2.0.4 on 2018-04-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180426_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='canton',
            field=models.CharField(default='', max_length=255, verbose_name='Cantón'),
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(default='', max_length=255, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='client',
            name='other_address',
            field=models.CharField(default='', max_length=255, verbose_name='Otras señas'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(default='', max_length=255, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(default='', max_length=255, verbose_name='Barrio'),
        ),
    ]
