# Generated by Django 2.0.4 on 2018-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180429_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='canton',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cantón'),
        ),
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Otras señas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='town',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Barrio'),
        ),
    ]
