# Generated by Django 2.0.4 on 2018-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Factura Cerrada'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pay_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('CRED', 'Crédito'), ('TRAN', 'Transferencia'), ('OTHER', 'Otro')], default='CASH', max_length=4, verbose_name='Tipo de Pago'),
        ),
    ]
