# Generated by Django 2.0.4 on 2018-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20180524_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_id',
            field=models.CharField(default='', max_length=40, verbose_name='ID del Proveedor'),
        ),
    ]
