# Generated by Django 2.0.4 on 2018-05-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
