# Generated by Django 2.0.4 on 2018-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20180524_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.TextField(default='', verbose_name='Bodega de Destino'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse_id',
            field=models.CharField(default='', max_length=40, verbose_name='ID de la Bodega'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.TextField(default='', verbose_name='Proveedor'),
        ),
    ]
