# Generated by Django 2.0.4 on 2018-04-26 04:24

import apps.senders.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_number', models.CharField(default='', max_length=255, verbose_name='Número de Identificación')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(default='', max_length=255, verbose_name='Nombre comercial')),
                ('phone_number', models.CharField(default='', max_length=255, verbose_name='Teléfono')),
                ('fax_number', models.CharField(default='', max_length=255, verbose_name='Fax')),
                ('province', models.CharField(default='', max_length=255, verbose_name='Provincia')),
                ('canton', models.CharField(default='', max_length=255, verbose_name='Cantón')),
                ('district', models.CharField(default='', max_length=255, verbose_name='Distrito')),
                ('town', models.CharField(default='', max_length=255, verbose_name='Barrio')),
                ('other_adress', models.CharField(default='', max_length=255, verbose_name='Otras señas')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
                ('key', models.ImageField(blank=True, upload_to=apps.senders.models.url)),
                ('pin', models.CharField(default='0000', max_length=4, verbose_name='PIN')),
                ('user', models.CharField(default='0000', max_length=255, verbose_name='Usuario del Token')),
                ('password', models.CharField(default='0000', max_length=255, verbose_name='Contraseña del Token')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Emisor',
                'verbose_name_plural': 'Emisores',
                'ordering': ['id_number'],
            },
        ),
    ]
