# Generated by Django 2.0.4 on 2018-04-26 04:44

import apps.senders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='key',
            field=models.FileField(blank=True, upload_to=apps.senders.models.url),
        ),
    ]
