# Generated by Django 2.0.4 on 2018-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0002_auto_20180425_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='fax_country_code',
            field=models.PositiveIntegerField(default=506, max_length=3, verbose_name='Código de país fax'),
        ),
        migrations.AddField(
            model_name='sender',
            name='phone_country_code',
            field=models.PositiveIntegerField(default=506, max_length=3, verbose_name='Código de país télefono'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='commercial_name',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='fax_number',
            field=models.CharField(default='', max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.PositiveIntegerField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
