# Generated by Django 2.0.4 on 2018-04-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0003_auto_20180426_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='other_adress',
            new_name='other_address',
        ),
    ]
