# Generated by Django 2.0.4 on 2018-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0004_auto_20180426_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='id_type',
            field=models.CharField(choices=[('01', 'Cédula Física'), ('02', 'Cédula Jurídica'), ('03', 'Pasaporte')], default='01', max_length=3, verbose_name='Tipo de Identificación'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='fax_country_code',
            field=models.CharField(default=506, max_length=3, verbose_name='Código de país fax'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_country_code',
            field=models.CharField(default=506, max_length=3, verbose_name='Código de país télefono'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
