# Generated by Django 2.0.4 on 2018-04-30 15:05

import apps.senders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0005_auto_20180426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.senders.models.logoUrl, verbose_name='Logo para Factura'),
        ),
        migrations.AddField(
            model_name='sender',
            name='logo_width',
            field=models.CharField(default='', max_length=6, verbose_name='Ancho del Logo'),
            preserve_default=False,
        ),
    ]
