# Generated by Django 2.0.4 on 2018-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0006_auto_20180430_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='logo_width',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Ancho del Logo'),
        ),
    ]
