# Generated by Django 2.0.4 on 2018-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0007_auto_20180430_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Emisor Por Defecto'),
        ),
    ]
